name: xo-install test
on: [push, pull_request]
jobs:
  Test-Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: xo-install run
        run: sudo ./xo-install.sh --install
        shell: bash
